version: '3'

services:
  app:
    container_name: projects
    image: node:lts-alpine
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - db
    ports:
      - ${CONTAINER_PORT:-3000}:${HOST_PORT:-3000}
    command: npm run start

  db:
    container_name: '${DB_HOST:-mysql}'
    build: ./database-service
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_USER=${DB_USER:-user}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
      - MYSQL_DATABASE=${DB_DATABASE:-projects}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-supersecret}