version: '3'

services:
  app:
    container_name: projects
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    depends_on:
      - db
    ports:
      - ${CONTAINER_PORT:-3000}:${HOST_PORT:-3000}
    command: ["-c", "/opt/wait-for.sh ${DB_HOST:-mysql}:${DB_PORT:-3306} && knex migrate:latest && npm run start"]
    entrypoint: ["/bin/sh"]

  db:
    container_name: '${DB_HOST:-mysql}'
    image: mysql:5.7
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_USER=${DB_USER:-user}
      - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
      - MYSQL_DATABASE=${DB_DATABASE:-projects}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-supersecret}